### ISSUE TITLE
Confused by some dimensions from reviewsWithHeader.csv dataset.

### ISSUE THREAD

**Issue by yzho0907** [mandeep147/Amazon-Product-Recommender-System#2]
what are these dimensions: 
HelpfulnessNumerator_x | HelpfulnessDenominator_x | overall_y | reviewText_y | reviewTime_y | reviewerID_y | reviewerName_y | summary_y | unixReviewTime_y | HelpfulnessNumerator_y | HelpfulnessDenominator_y ? and how can i get these information? thx a lot

**Comment by mandeep147** [comment]
It is the dataset produced after merging (right joining) the original df and the one produced by `count = df.groupby("asin", as_index=False).count()` which calculates the count of each product. y-dimensions represent the count. Hope that clarifies the confusion.

**Comment by yzho0907** [comment]
@mandeep147 OH I SEE, that does explain all the y-dimensions! any idea about these two: HelpfulnessNumerator_x | HelpfulnessDenominator_x? thx again!

**Comment by mandeep147** [comment]
If you look into the dataset, there is a field `helpful` which is an array of 2 values, `HelpfulnessNumerator_x` and `HelpfulnessDenominator_x` is the split of that array object to find the percentage of the usefulness of the particular review.

**Comment by AnandDadhich** [comment]
will you please forward me reviewsWithHeader.csv and after all what are the fields in this dfReviews.csv
